name: CECAM_tutorial
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.4.0
  - attrs=23.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - bleach=6.0.0
  - ca-certificates=2023.7.22
  - cffi=1.15.1
  - comm=0.1.4
  - debugpy=1.7.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - gmp=6.2.1
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.1
  - ipykernel=6.25.2
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.2
  - jedi=0.19.0
  - jinja2=3.1.2
  - jsonschema=4.19.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.3.1
  - jupyter_core=5.3.1
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=1.0.0
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.24
  - libsodium=1.0.18
  - libsqlite=3.43.0
  - libstdcxx-ng=13.2.0
  - libzlib=1.2.13
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mistune=3.0.1
  - nbclient=0.8.0
  - nbconvert=7.8.0
  - nbconvert-core=7.8.0
  - nbconvert-pandoc=7.8.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nglview=1.1.7
  - notebook=6.3.0
  - openssl=1.1.1w
  - packaging=23.1
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - prometheus_client=0.17.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.16.1
  - python=3.9.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.0
  - python_abi=3.9
  - pyzmq=25.1.1
  - readline=8.2
  - referencing=0.30.2
  - rpds-py=0.10.2
  - send2trash=1.8.2
  - setuptools=68.1.2
  - six=1.16.0
  - soupsieve=2.5
  - sqlite=3.43.0
  - stack_data=0.6.2
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.9.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - wheel=0.41.2
  - widgetsnbextension=3.6.0
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.13
  - pip:
    - aniso8601==9.0.1
    - anyio==4.0.0
    - ase==3.19.3
    - biopython==1.81
    - bitarray==2.8.1
    - cachetools==5.3.1
    - certifi==2023.7.22
    - charset-normalizer==3.2.0
    - click==8.1.7
    - contourpy==1.1.0
    - cryptography==41.0.3
    - cycler==0.11.0
    - deprecation==2.1.0
    - docstring-parser==0.15
    - ecdsa==0.18.0
    - elasticsearch==7.17.9
    - elasticsearch-dsl==7.4.0
    - emmet-core==0.57.0
    - et-xmlfile==1.1.0
    - fasteners==0.18
    - fonttools==4.42.1
    - future==0.18.3
    - griddataformats==1.0.1
    - gsd==3.1.1
    - h11==0.14.0
    - h5py==3.9.0
    - hjson==3.1.0
    - httpcore==0.18.0
    - httpx==0.25.0
    - idna==3.4
    - jmespath==1.0.1
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - latexcodec==2.0.1
    - lxml==4.9.3
    - matplotlib==3.7.3
    - mda-xdrlib==0.2.0
    - mdanalysis==2.5.0
    - memoization==0.4.0
    - mmtf-python==1.1.3
    - monty==2023.9.5
    - mp-api==0.36.0
    - mpmath==1.3.0
    - mrcfile==1.4.3
    - msgpack==1.0.5
    - networkx==3.1
    - nomad-lab==1.2.0
    - nptyping==1.4.4
    - numpy==1.22.4
    - openpyxl==3.1.2
    - orjson==3.6.0
    - palettable==3.3.3
    - pandas==1.5.3
    - panedr==0.7.2
    - parmed==4.1.0
    - pbr==5.11.1
    - phonopy==2.11.0
    - pillow==10.0.0
    - pint==0.17
    - plotly==5.16.1
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pybtex==0.24.0
    - pydantic==1.10.12
    - pyedr==0.7.2
    - pymatgen==2023.2.28
    - pyparsing==3.1.1
    - python-jose==3.3.0
    - python-keycloak==3.3.0
    - python-magic==0.4.24
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - requests==2.31.0
    - requests-toolbelt==1.0.0
    - rfc3161ng==2.1.3
    - rsa==4.9
    - ruamel-yaml==0.17.32
    - ruamel-yaml-clib==0.2.7
    - scikit-learn==1.3.0
    - scipy==1.11.2
    - sniffio==1.3.0
    - spglib==2.1.0
    - style==1.1.0
    - sympy==1.12
    - tabulate==0.9.0
    - tenacity==8.2.3
    - threadpoolctl==3.2.0
    - toposort==1.10
    - tqdm==4.66.1
    - typish==1.9.3
    - uncertainties==3.1.7
    - update==0.0.1
    - urllib3==1.26.16
    - wrapt==1.15.0
    - xarray==2023.8.0
